# Webapp/frontend/Dockerfile_frontend
FROM node:20-alpine as build 
WORKDIR /app
COPY package.json package-lock.json* ./ 
RUN npm ci || npm install 
COPY . .
RUN npm run build 

FROM nginx:alpine as production 
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]