# Webapp/backend/Dockerfile_backend

# Use a Python 3.10 or 3.11 base image
FROM python:3.10-slim-buster 

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 5000