"""ensure all tables are created

Revision ID: fb3a5a7ed0bc
Revises: 
Create Date: 2025-06-05 09:22:16.717819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3a5a7ed0bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('greenhouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('ideal_temp_min', sa.Float(), nullable=True),
    sa.Column('ideal_temp_max', sa.Float(), nullable=True),
    sa.Column('ideal_groundmoisture', sa.Float(), nullable=True),
    sa.Column('ideal_humidity', sa.Float(), nullable=True),
    sa.Column('ideal_co2', sa.Float(), nullable=True),
    sa.Column('ideal_light', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('datatype', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('actuators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('plants_id', sa.Integer(), nullable=True),
    sa.Column('greenhouse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouses.id'], ),
    sa.ForeignKeyConstraint(['plants_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('plants_id', sa.Integer(), nullable=True),
    sa.Column('greenhouse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouses.id'], ),
    sa.ForeignKeyConstraint(['plants_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_greenhouse',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('greenhouse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'greenhouse_id')
    )
    op.create_table('actuators_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('actuators_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actuators_id'], ['actuators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('sensors_id', sa.Integer(), nullable=False),
    sa.Column('units_id', sa.Integer(), nullable=False),
    sa.Column('greenhouse_id_direct', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['greenhouse_id_direct'], ['greenhouses.id'], ),
    sa.ForeignKeyConstraint(['sensors_id'], ['sensors.id'], ),
    sa.ForeignKeyConstraint(['units_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_data')
    op.drop_table('actuators_log')
    op.drop_table('user_greenhouse')
    op.drop_table('sensors')
    op.drop_table('auth_tokens')
    op.drop_table('actuators')
    op.drop_table('users')
    op.drop_table('units')
    op.drop_table('plants')
    op.drop_table('greenhouses')
    # ### end Alembic commands ###
